models/Product.py
from utils.db import db

class Producto(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nombre= db.Column(db.String(100))
    precio = db.Column(db.Integer)
    stock = db.Column(db.Integer)
    descripcion = db.Column(db.String(100))

    def __init__(self,nombre,precio,stock,descripcion):
        self.nombre= nombre
        self.precio = precio
        self.stock = stock
        self.descripcion = descripcion
    
    #lista de funciones get que retornaran los datos de la base de datos
    def get_id(self):
        return self.id
    def get_nombre(self):
        return self.nombre
    def get_precio(self):
        return self.precio
    def get_stock(self):
        return self.stock

models/cliente.py
from utils.db import db

class Cliente(db.Model):
    rut = db.Column(db.Integer, primary_key=True)
    nombre= db.Column(db.String(100))
    apellido = db.Column(db.String(100))
    correo = db.Column(db.String(100))

    def __init__(self,rut,nombre,apellido,correo):
        self.rut= rut
        self.nombre= nombre
        self.apellido = apellido
        self.correo = correo
    
    def get_rut(self):
        return self.rut
    def get_nombre(self):
        return self.nombre
    def get_apellido(self):
        return self.apellido
    def get_correo(self):
        return self.correo
    

models/venta.py
from utils.db import db

class venta(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    rut = db.Column(db.String(100))
    nombre = db.Column(db.String(100))
    apellido = db.Column(db.String(100))
    correo = db.Column(db.String(100))
    nombre_producto = db.Column(db.String(100))
    total_precio = db.Column(db.Integer)

    def __init__(self,rut,nombre,apellido,correo,nombre_producto,total_precio):
        self.rut= rut
        self.nombre = nombre
        self.apellido = apellido
        self.correo = correo
        self.nombre_producto = nombre_producto
        self.total_precio = total_precio

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from routes.contacts import contacts

app = Flask(__name__)

app.config["SQLALCHEMY_DATABASE_URI"] = "mysql://root:0007@localhost/tienda"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

SQLAlchemy(app)


app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.cliente import Cliente
from models.Product import Producto
from models.venta import venta
from utils.db import db

contacts = Blueprint("contacts", __name__)

@contacts.route('/')
def index():
    return render_template('home.html')
#---------------------CLIENTES---------------------
@contacts.route('/new', methods=['POST'])
def add_contact():
    rut=request.form['rut']
    nombre=request.form['Nombre']
    apelldio=request.form['Apellido']
    correo=request.form['Correo']

    cl = Cliente(rut,nombre,apelldio,correo)

    db.session.add(cl)
    db.session.commit()
    return redirect(url_for('contacts.index'))

@contacts.route('/delete/<rut>')
def delete_contact(rut):
    contacts = Cliente.query.get(rut)
    db.session.delete(contacts)
    db.session.commit()
    return redirect(url_for('contacts.lista'))

@contacts.route('/update/<rut>', methods=['POST', 'GET'])
def update_contact(rut):
    if request.method == 'POST':
        contacts = Cliente.query.get(rut)
        contacts.rut = request.form['rut']
        contacts.nombre = request.form['Nombre']
        contacts.apellido = request.form['Apellido']
        contacts.correo = request.form['Correo']
        db.session.commit()
        return redirect(url_for('contacts.lista'))
    
    contact = Cliente.query.get(rut)
    return render_template('update.html', contact=contact)
@contacts.route('/añadir')
def añadir():
    return render_template('añadir.html')
@contacts.route('/lista')
def lista():
    contacts = Cliente.query.all()
    return render_template('lista.html',contacts=contacts)
#---------------------PRODUCTOS---------------------    
@contacts.route('/add_product', methods=['POST'])
def add_product():
    nombre=request.form['nombre']
    precio=request.form['precio']
    stock=request.form['stock']
    descripcion=request.form['descripcion']

    pr = Producto(nombre,precio,stock,descripcion)

    db.session.add(pr)
    db.session.commit()
    return redirect(url_for('contacts.index'))

@contacts.route('/añadir_producto')
def añadir_producto():
    return render_template('product.html')

@contacts.route('/lista_productos')
def lista_productos():
    product = Producto.query.all()
    return render_template('lista_productos.html',products=product)

@contacts.route('/delete_product/<id>')
def delete_product(id):
    product = Producto.query.get(id)
    db.session.delete(product)
    db.session.commit()
    return redirect(url_for('contacts.lista_productos'))

@contacts.route('/update_product/<id>', methods=['POST', 'GET'])
def update_product(id):
    if request.method == 'POST':
        product = Producto.query.get(id)
        product.nombre = request.form['nombre']
        product.precio = request.form['precio']
        product.stock = request.form['stock']
        product.descripcion = request.form['descripcion']
        db.session.commit()
        return redirect(url_for('contacts.lista_productos'))
    
    product = Producto.query.get(id)
    return render_template('update_product.html', product=product)

#---------------------VENTAS---------------------
@contacts.route('/add_venta', methods=['POST', 'GET'])
def add_venta():
    user_id=request.form['user_id']
    product_id=request.form['p_id']
    products=Producto.query.get(product_id)
    users=Cliente.query.get(user_id)
    rut=users.rut
    nombre=users.nombre
    apellido=users.apellido
    correo=users.correo

    nombre_producto=products.nombre
    total_precio=int(products.precio)*int(request.form['cantidad'])
    
    ve = venta(rut,nombre,apellido,correo,nombre_producto,total_precio)

    db.session.add(ve)
    db.session.commit()
    return redirect(url_for('contacts.index'))


@contacts.route('/añadir_venta')
def añadir_venta():
    products=Producto.query.all()
    users=Cliente.query.all()
    return render_template('venta.html',users=users,products=products)


@contacts.route('/lista_ventas')
def lista_ventas():
    ventas = venta.query.all()
    return render_template('lista_ventas.html',ventas=ventas)

@contacts.route('/delete_venta/<id>')
def delete_venta(id):
    ventas = venta.query.get(id)
    db.session.delete(ventas)
    db.session.commit()
    return redirect(url_for('contacts.lista_ventas'))

templates/añadir.html
<form action="/new" method="POST">
    <input type="text" name="rut" placeholder="Ingresar Rut">
    <input type="text" name="Nombre" placeholder="Ingresar Nombre">
    <input type="text" name="Apellido" placeholder="Ingresar Apellido">
    <input type="text" name="Correo" placeholder="Ingresar Correo">

    <button>Save</button>
</form>

<div>
    <a href="{{ url_for('contacts.index') }}">Volver Atras</a>
</div>

<style>
    form {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    form input {
        margin: 10px;
    }

    form button {
        margin: 10px;
    }

    div {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: center;
    }

    div a {
        margin: 10px;
    }
    button{
        background-color: #f5f5f5;
        border: 1px solid black;
        border-radius: 10px;
    }
    button:hover{
        background-color: black;
        color: #f5f5f5;
    }
    a{
        text-decoration: none;
        color: black;
        font-size: 20px;
        margin: 10px;
    }
    a:hover{
        color: #f5f5f5;
        background-color: black;
        border-radius: 10px;
    }
</style>

templates/dictionary_form.html
<table>
    {% for key,value in data.items() %}
    <tr>
        <th>
            {{key}}
        </th>
        <td>
            {{value}}
        </td>
    {% endfor %}
    </tr>
</table>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div >
        <a href="{{ url_for('contacts.añadir') }}">Añadir Usuarios</a>
        <a href="{{ url_for('contacts.lista') }}">Ver Usuarios</a>
        
    </div>
    <div>
        <a href="{{ url_for('contacts.añadir_producto') }}">Añadir Producto</a>
        <a href="{{ url_for('contacts.lista_productos') }}">Ver Productos</a>
    </div>
    <div>
        <a href="{{ url_for('contacts.añadir_venta') }}">Añadir Venta</a>
        <a href="{{ url_for('contacts.lista_ventas') }}">Ver Ventas</a>
    </div>
</body>

<style>
    body{
        background-color: #f5f5f5;
    }
    div{
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: row;
    }
    a{
        text-decoration: none;
        color: black;
        font-size: 20px;
        margin: 10px;
    }
    a:hover{
        color: #f5f5f5;
        background-color: black;
        border-radius: 10px;
    }
</style>
</html>

templates/index.html
<div>
    {% for contact in contacts %}
    <div>
        <a href="{{ url_for('contacts.delete_contact', rut=contact.rut) }}">Delete</a>
        <a href="{{ url_for('contacts.update_contact', rut=contact.rut) }}">Update</a>
        <h5>{{contact.nombre}}</h5>
        <p>{{contact.rut}}</p>
        <p>{{contact.apellido}}</p>
        <p>{{contact.correo}}</p>
    </div>
    {% endfor %}
</div>

templates/lista.html
<nav>
    <a href="{{ url_for('contacts.añadir') }}">Añadir Usuarios</a>
    <a href="{{ url_for('contacts.index') }}">Inicio</a>
</nav>
<div>
    {% for contact in contacts %}
    <div>
        <nav>
            <a href="{{ url_for('contacts.delete_contact', rut=contact.rut) }}">Delete</a>
            <a href="{{ url_for('contacts.update_contact', rut=contact.rut) }}">Update</a>
        </nav>
        <h5>Nombre: {{contact.nombre}}</h5>
        <p>Rut: {{contact.rut}}</p>
        <p>Apellido: {{contact.apellido}}</p>
        <p>Correo: {{contact.correo}}</p>
    </div>
    {% endfor %}
</div>
<style>
    * {
        margin: 8px;
        padding: 0px;
    }
    div {
        display: flex;
        flex-direction: row;
        align-items: center;
    }
    div div {
        display: flex;
        flex-direction: column;
        align-items: center;
        border: 1px solid black;
        width: 300px;
        margin: 10px;
    }
    div div a {
        margin: 1px;
    }
    nav {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: center;
    }
    a{
        text-decoration: none;
        color: black;
        font-size: 20px;
        margin: 10px;
    }
    a:hover{
        color: #f5f5f5;
        background-color: black;
        border-radius: 10px;
    }
</style>

templates/lista_productos.html
<nav>
    <a href="{{ url_for('contacts.añadir_producto') }}">Añadir Producto</a>
    <a href="{{ url_for('contacts.index') }}">Inicio</a>
</nav>
<div>
    {% for product in products %}
    <div>
        <nav>
            <a href="{{ url_for('contacts.delete_product', id=product.id) }}">Delete</a>
            <a href="{{ url_for('contacts.update_product', id=product.id) }}">Update</a>
        </nav>
        <h5>Nombre: {{product.nombre}}</h5>
        <p>Id: {{product.id}}</p>
        <p>Descripcion: {{product.descripcion}}</p>
        <p>Precio: {{product.precio}}</p>
        <p>Stock: {{product.stock}}</p>
    </div>
    {% endfor %}
</div>
<style>
    * {
        margin: 8px;
        padding: 0px;
    }
    div {
        display: flex;
        flex-direction: row;
        align-items: center;
    }
    div div {
        display: flex;
        flex-direction: column;
        align-items: center;
        border: 1px solid black;
        width: 300px;
        margin: 10px;
    }
    div div a {
        margin: 1px;
    }
    nav {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: center;
    }
    a{
        text-decoration: none;
        color: black;
        font-size: 20px;
        margin: 10px;
    }
    a:hover{
        color: #f5f5f5;
        background-color: black;
        border-radius: 10px;
    }
</style>

templates/lista_ventas.html
<nav>
    <a href="{{ url_for('contacts.añadir_venta') }}">Añadir Venta</a>
    <a href="{{ url_for('contacts.index') }}">Inicio</a>
</nav>
<div>
    {% for venta in ventas %}
    <div>
        <nav>
            <a href="{{ url_for('contacts.delete_venta', id=venta.id) }}">Delete</a>
        </nav>
        <h5>Nombre: {{venta.nombre}}</h5>
        <p>Rut: {{venta.rut}}</p>
        <p>Venta Id: {{venta.id}}</p>
        <p>Apellido: {{venta.apellido}}</p>
        <p>Correo: {{venta.correo}}</p>
        <p>----------------</p>
        <p>Nombre Producto: {{venta.nombre_producto}}</p>
        <p>Total Precio: {{venta.total_precio}}</p>
    </div>
    {% endfor %}
</div>
<style>
    * {
        margin: 8px;
        padding: 0px;
    }
    div {
        display: flex;
        flex-direction: row;
        align-items: center;
    }
    div div {
        display: flex;
        flex-direction: column;
        align-items: center;
        border: 1px solid black;
        width: 300px;
        margin: 10px;
    }
    div div a {
        margin: 1px;
    }
    nav {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: center;
    }
    a{
        text-decoration: none;
        color: black;
        font-size: 20px;
        margin: 10px;
    }
    a:hover{
        color: #f5f5f5;
        background-color: black;
        border-radius: 10px;
    }
</style>

templates/product.html
<form action="/add_product" method="POST">
    <input type="text" name="nombre" placeholder="Ingresar Nombre">
    <input type="text" name="precio" placeholder="Ingresar Precio">
    <input type="text" name="stock" placeholder="Ingresar Stock">
    <input type="text" name="descripcion" placeholder="Ingresar Descripcion">
    <button>Save</button>
</form>
<div>
    <a href="{{ url_for('contacts.index') }}">Volver Atras</a>
</div>

<style>
    form {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }
    form input {
        margin: 10px;
    }
    form button {
        margin: 10px;
    }
    div {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: center;
    }
    div a {
        margin: 10px;
    }
    button{
        background-color: #f5f5f5;
        border: 1px solid black;
        border-radius: 10px;
    }
    button:hover{
        background-color: black;
        color: #f5f5f5;
    }
    a{
        text-decoration: none;
        color: black;
        font-size: 20px;
        margin: 10px;
    }
    a:hover{
        color: #f5f5f5;
        background-color: black;
        border-radius: 10px;
    }
</style>

templates/update.html
<form action="/update/{{contact.rut}}" method="post">
    <input type="text" name="rut" placeholder="Ingresar Rut" value="{{contact.rut}}">
    <input type="text" name="Nombre" placeholder="Ingresar Nombre" value="{{contact.nombre}}">
    <input type="text" name="Apellido" placeholder="Ingresar Apellido" value="{{contact.apellido}}">
    <input type="text" name="Correo" placeholder="Ingresar Correo" value="{{contact.correo}}">
    <button>Save</button>
</form>


<div>
    <a href="{{ url_for('contacts.index') }}">Volver Atras</a>
</div>

<style>
    form {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    form input {
        margin: 10px;
    }

    form button {
        margin: 10px;
    }

    div {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: center;
    }

    div a {
        margin: 10px;
    }
    button{
        background-color: #f5f5f5;
        border: 1px solid black;
        border-radius: 10px;
    }
    button:hover{
        background-color: black;
        color: #f5f5f5;
    }
    a{
        text-decoration: none;
        color: black;
        font-size: 20px;
        margin: 10px;
    }
    a:hover{
        color: #f5f5f5;
        background-color: black;
        border-radius: 10px;
    }
</style>

templates/update_product.html
<form action="/update_product/{{product.id}}" method="POST">
    <input type="text" name="nombre" placeholder="Ingresar Nombre" value="{{product.nombre}}">
    <input type="text" name="descripcion" placeholder="Ingresar Descripcion" value="{{product.descripcion}}">
    <input type="text" name="stock" placeholder="Ingresar stock" value="{{product.stock}}">
    <input type="text" name="precio" placeholder="Ingresar Precio" value="{{product.precio}}">
    <button>Save</button>
</form>
<div>
    <a href="{{ url_for('contacts.lista_productos') }}">Volver Atras</a>
</div>
<style>
    form {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }
    form input {
        margin: 10px;
    }
    form button {
        margin: 10px;
    }
    div {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: center;
    }
    div a {
        margin: 10px;
    }
    button{
        background-color: #f5f5f5;
        border: 1px solid black;
        border-radius: 10px;
    }
    button:hover{
        background-color: black;
        color: #f5f5f5;
    }
    a{
        text-decoration: none;
        color: black;
        font-size: 20px;
        margin: 10px;
    }
    a:hover{
        color: #f5f5f5;
        background-color: black;
        border-radius: 10px;
    }
</style>

templates/venta.html
<form action="/add_venta" method="POST">
        <select name="user_id">
            {% for user in users %}
            <option value="{{user.rut}}">{{user.nombre}}</option>
            {% endfor %}
        </select>
        <select name="p_id">
            {% for producto in products %}
            <option value="{{producto.id}}">{{producto.nombre}}</option>
            {% endfor %}
        </select>
    <input type="text" name="cantidad" placeholder="Ingresar Cantidad">
    <button>Save</button>
</form>

<div>
    <a href="{{ url_for('contacts.index') }}">Volver Atras</a>
</div>

<style>
    select{
        margin: 10px;
    }
    form {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    form input {
        margin: 10px;
    }

    form button {
        margin: 10px;
    }

    div {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: center;
    }

    div a {
        margin: 10px;
    }
    button{
        background-color: #f5f5f5;
        border: 1px solid black;
        border-radius: 10px;
    }
    button:hover{
        background-color: black;
        color: #f5f5f5;
    }
    a{
        text-decoration: none;
        color: black;
        font-size: 20px;
        margin: 10px;
    }
    a:hover{
        color: #f5f5f5;
        background-color: black;
        border-radius: 10px;
    }
</style>